site_name: Paper Analysis documentation
nav:
  - Home: index.md
  - Install: install.md
  - Usage: usage.md
  - Output: output.md
theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true